### ISSUE TITLE
Uncaught TypeError: composeWithTracker is not a function

### ISSUE THREAD

**Issue by barrymichaeldoyle** [themeteorchef/getting-started-with-react-router-v4#1]
I get the following error in my App.js file when running the application:

Uncaught TypeError: composeWithTracker is not a function

What am I doing wrong? I've got react-komposer imported

**Comment by themeteorchef** [comment]
@barrydoyle18 did you run `npm install` before you started up the app? If not, this error is likely because `react-komposer` isn't installed in the app.

**Comment by barrymichaeldoyle** [comment]
Ah, yeah I sorted it out. It did have something to do with that. Thanks for getting back to me 👍
